<?php
$config = array(
    'per_page'         => 5,
    'use_page_numbers' => TRUE,
    'num_links'        => 5,
    'full_tag_open'    => '<ul class="pagination">',
    'full_tag_close'   => '</ul>',
    'num_tag_open'     => '<li>',
    'num_tag_cloes'    => '</li>',
    'cur_tag_open'     => '<li class="current"><a>',
    'cur_tag_close'    => '</a></li>',
    'next_tag_open'    => '<li>',
    'next_tag_close'   => '</li>',
    'pre_tag_open'     => '<li>',
    'pre_tag_close'    => '</li>',
    'first_link'       => '&laquo;',
    'first_tag_open'   => '<li class="arrow">',
    'first_tag_close'  => '</li>',
    'last_link'        => '&raquo;',
    'last_tag_open'    => '<li class="arrow">',
    'last_tag_close'   => '</li>',
    'next_tag_open'    => '<li class="arrow">',
    'next_tag_close'    => '</li>',
    'prev_tag_open'    => '<li class="arrow">',
    'prev_tag_close'    => '</li>',
);